export const REQUEST_RESULTS = 'explorer/REQUEST_RESULTS';
export const RECEIVE_FAILURE = 'explorer/RECEIVE_FAILURE';
export const RECEIVE_RESULTS = 'explorer/RECEIVE_RESULTS';
export const SET_FORM_OPTIONS = 'explorer/SET_FORM_OPTIONS';
export const REQUEST_FORM_OPTIONS = 'explorer/REQUEST_FORM_OPTIONS';
export const SET_TRADE_FLOW_SUBGROUPS = 'explorer/SET_TRADE_FLOW_SUBGROUPS';
export const SET_REPORTER_SUBGROUPS = 'explorer/SET_REPORTER_SUBGROUPS';